"""
misc.py - collection of all kinds of stuff
"""

LORE_IPSUM = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Malesuada pellentesque elit eget gravida cum. Sed id semper risus in hendrerit. Dui vivamus arcu felis bibendum ut tristique et. Felis imperdiet proin fermentum leo vel orci. Sit amet facilisis magna etiam tempor orci eu lobortis. Enim ut tellus elementum sagittis. Nulla at volutpat diam ut venenatis tellus in metus vulputate. Phasellus faucibus scelerisque eleifend donec pretium vulputate. Cras adipiscing enim eu turpis egestas pretium aenean. Tincidunt augue interdum velit euismod in pellentesque massa. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere. Auctor augue mauris augue neque gravida in. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Morbi tristique senectus et netus et malesuada fames ac.

Amet tellus cras adipiscing enim eu turpis egestas pretium. Orci nulla pellentesque dignissim enim sit. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Enim neque volutpat ac tincidunt vitae semper quis. Ullamcorper eget nulla facilisi etiam. Proin sed libero enim sed. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Adipiscing bibendum est ultricies integer quis auctor elit sed vulputate. Elit at imperdiet dui accumsan sit amet nulla facilisi. Augue eget arcu dictum varius duis. Tortor posuere ac ut consequat semper viverra nam libero. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. Magna fermentum iaculis eu non diam phasellus vestibulum lorem.

Faucibus interdum posuere lorem ipsum dolor sit. Nulla pellentesque dignissim enim sit. Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Cras ornare arcu dui vivamus. Interdum varius sit amet mattis vulputate. Enim nulla aliquet porttitor lacus luctus. Vitae justo eget magna fermentum. Auctor elit sed vulputate mi sit amet mauris commodo quis. Congue eu consequat ac felis donec et odio pellentesque diam. Urna molestie at elementum eu facilisis sed. In metus vulputate eu scelerisque felis imperdiet proin. Sollicitudin ac orci phasellus egestas.

Consectetur a erat nam at lectus urna duis convallis convallis. Justo donec enim diam vulputate ut pharetra sit. Sagittis purus sit amet volutpat consequat mauris. Placerat vestibulum lectus mauris ultrices. Feugiat nibh sed pulvinar proin. Placerat orci nulla pellentesque dignissim enim. Dui accumsan sit amet nulla facilisi. Magna sit amet purus gravida quis. Id donec ultrices tincidunt arcu non sodales. Volutpat sed cras ornare arcu dui.

Pharetra pharetra massa massa ultricies. Lacus luctus accumsan tortor posuere ac. Libero justo laoreet sit amet cursus. Posuere morbi leo urna molestie at elementum eu facilisis. Arcu ac tortor dignissim convallis. Euismod nisi porta lorem mollis aliquam ut. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Praesent semper feugiat nibh sed pulvinar. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Sed ullamcorper morbi tincidunt ornare massa eget egestas. Cras semper auctor neque vitae tempus quam pellentesque.

Nibh praesent tristique magna sit amet. Id porta nibh venenatis cras. Dictumst vestibulum rhoncus est pellentesque elit. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Purus gravida quis blandit turpis cursus in. Mattis pellentesque id nibh tortor id aliquet. A diam sollicitudin tempor id eu nisl nunc mi. At volutpat diam ut venenatis tellus in metus vulputate. Imperdiet dui accumsan sit amet nulla facilisi morbi. Morbi tristique senectus et netus. Sit amet massa vitae tortor condimentum. Fusce ut placerat orci nulla pellentesque. In hac habitasse platea dictumst vestibulum rhoncus est. Lectus urna duis convallis convallis tellus id. Euismod in pellentesque massa placerat duis ultricies. Vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra. Imperdiet proin fermentum leo vel orci porta non. Auctor neque vitae tempus quam pellentesque nec nam.

Pharetra pharetra massa massa ultricies mi quis hendrerit dolor. Neque ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Adipiscing at in tellus integer feugiat scelerisque varius. Maecenas ultricies mi eget mauris pharetra et. Luctus venenatis lectus magna fringilla. Aliquet risus feugiat in ante metus dictum at tempor commodo. Tellus at urna condimentum mattis pellentesque id nibh. Nec feugiat in fermentum posuere urna nec tincidunt. Adipiscing elit ut aliquam purus sit amet luctus. Lobortis feugiat vivamus at augue eget arcu dictum varius duis. Interdum consectetur libero id faucibus nisl tincidunt.

Metus dictum at tempor commodo ullamcorper a lacus vestibulum. Nullam ac tortor vitae purus faucibus. Mattis rhoncus urna neque viverra justo. Et egestas quis ipsum suspendisse. Erat velit scelerisque in dictum non consectetur a erat nam. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere. Faucibus scelerisque eleifend donec pretium vulputate sapien. Nunc sed id semper risus in. Nibh nisl condimentum id venenatis a condimentum vitae sapien. Nullam vehicula ipsum a arcu cursus vitae congue.

Aenean vel elit scelerisque mauris. Leo vel fringilla est ullamcorper eget nulla facilisi etiam. Magna fermentum iaculis eu non diam phasellus vestibulum lorem sed. Lectus urna duis convallis convallis tellus id. Facilisi nullam vehicula ipsum a arcu cursus. Tincidunt eget nullam non nisi est sit. Dictum at tempor commodo ullamcorper a lacus vestibulum sed arcu. Blandit massa enim nec dui nunc mattis enim ut tellus. Duis ut diam quam nulla porttitor massa id neque. Blandit aliquam etiam erat velit scelerisque in dictum. At consectetur lorem donec massa sapien faucibus et. Tempor commodo ullamcorper a lacus vestibulum sed arcu non odio. Netus et malesuada fames ac turpis egestas integer. Consectetur lorem donec massa sapien. Urna porttitor rhoncus dolor purus non.

Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Purus sit amet luctus venenatis lectus magna fringilla. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Nulla facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Orci dapibus ultrices in iaculis nunc sed augue lacus. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue. Velit egestas dui id ornare arcu odio ut sem nulla. Sed odio morbi quis commodo. Sagittis orci a scelerisque purus semper eget duis at tellus. Nunc id cursus metus aliquam eleifend mi in nulla. Sit amet nisl suscipit adipiscing bibendum est ultricies. Felis eget nunc lobortis mattis aliquam.
"""